//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstLearningBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiswaWalimurid
    {
        public int ID { get; set; }
        public Nullable<int> IDSiswa { get; set; }
        public Nullable<int> IDWalimurid { get; set; }
    
        public virtual Siswa Siswa { get; set; }
        public virtual Walimurid Walimurid { get; set; }
    }
}
