//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFirstLearningBusiness
{
    using System;
    using System.Collections.Generic;
    
    public partial class Walimurid
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Walimurid()
        {
            this.Siswas = new HashSet<Siswa>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public string Pekerjaan { get; set; }
        public string JenisKelamin { get; set; }
        public string Hubungan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Siswa> Siswas { get; set; }
    }
}
